// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeCng5BpHdiNp3PltCaVIDXaQ2BfeYccQ',
    appId: '1:675912078802:web:0b781dc332d07d0212e40b',
    messagingSenderId: '675912078802',
    projectId: 'e-farm-esrl',
    authDomain: 'e-farm-esrl.firebaseapp.com',
    storageBucket: 'e-farm-esrl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz4oLAQZjerx7edOGOxnTz5CTz5MIi48o',
    appId: '1:675912078802:android:61be3b86f49dd78c12e40b',
    messagingSenderId: '675912078802',
    projectId: 'e-farm-esrl',
    storageBucket: 'e-farm-esrl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7ooUDNN03t1PDQQ0O-f8eQvwrLpwQI64',
    appId: '1:675912078802:ios:6ee02e8b2023159212e40b',
    messagingSenderId: '675912078802',
    projectId: 'e-farm-esrl',
    storageBucket: 'e-farm-esrl.appspot.com',
    iosClientId: '675912078802-336uprfb2dbc54mdf6lm6bq3101vevhn.apps.googleusercontent.com',
    iosBundleId: 'com.esrl.efarm.efarm',
  );
}
